FROM python:3.6
RUN apt-get update -y && \
    apt-get install -y python-pip python-dev &&\
    python -m pip install --upgrade setuptools wheel

WORKDIR /app

EXPOSE 5000

COPY requirements.txt requirements.txt
COPY . . 
RUN pip install -r requirements.txt
RUN pip install -e .

CMD ["uwsgi", "--ini", "vidura_wsgi.ini"]
