version: 2.1

#########
# Common
#########
orbs:
  

############
# Workflows
############
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
##################
# Job Definitions
##################
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . env/bin/activate
            ./sanity.sh