version: 2.1

#########
# Common
#########
orbs:
  slack: circleci/slack@3.4.2

############
# Workflows
############
workflows:
  version: 2
  build-deploy:
    jobs:
      - build

##################
# Job Definitions
##################
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            ./sanity.sh