"""empty message

Revision ID: 4c737484a6f7
Revises: 
Create Date: 2020-04-21 04:07:29.712451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c737484a6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_ID', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.String(length=128), nullable=True),
    sa.Column('runtime', sa.String(length=128), nullable=True),
    sa.Column('plot', sa.Text(), nullable=True),
    sa.Column('genre', sa.JSON(), nullable=True),
    sa.Column('director', sa.JSON(), nullable=True),
    sa.Column('writer', sa.JSON(), nullable=True),
    sa.Column('actors', sa.JSON(), nullable=True),
    sa.Column('language', sa.JSON(), nullable=True),
    sa.Column('country', sa.JSON(), nullable=True),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('imdb_rating', sa.String(length=128), nullable=True),
    sa.Column('rotten_tomatoes', sa.String(length=128), nullable=True),
    sa.Column('metascore', sa.String(length=128), nullable=True),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('box_office', sa.String(length=128), nullable=True),
    sa.Column('added_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_ID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('fb_handle', sa.String(length=255), nullable=True),
    sa.Column('g_handle', sa.String(length=255), nullable=True),
    sa.Column('twitter_handle', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###
