"""empty message

Revision ID: 55864804f614
Revises: 75aa6695c079
Create Date: 2020-04-20 19:33:08.878508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55864804f614'
down_revision = '75aa6695c079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_ID', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('genre', sa.JSON(), nullable=True),
    sa.Column('director', sa.JSON(), nullable=True),
    sa.Column('writer', sa.JSON(), nullable=True),
    sa.Column('actors', sa.JSON(), nullable=True),
    sa.Column('plot', sa.Text(), nullable=True),
    sa.Column('language', sa.JSON(), nullable=True),
    sa.Column('country', sa.JSON(), nullable=True),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('ratings', sa.JSON(), nullable=True),
    sa.Column('rotten_tomatoes', sa.Integer(), nullable=True),
    sa.Column('metascore', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('box_office', sa.String(length=128), nullable=True),
    sa.Column('added_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
